---
- name: Install Bind9 # https://www.ionos.com/digitalguide/server/configuration/how-to-make-your-raspberry-pi-into-a-dns-server/
  hosts: all
  become: yes
  tasks:
    - name: Update APT package manager repositories cache
      apt:
        update_cache: yes
    - name: Upgrade installed packages
      apt:
        upgrade: dist
    - name: Get current hostname
      command: hostname
      register: current_hostname
      changed_when: false

    - name: Set the hostname (only if different)
      hostname:
        name: "{{ host_name }}"
      when: current_hostname.stdout != host_name

    - name: Update /etc/hostname (only if different)
      copy:
        content: "{{ host_name }}\n"
        dest: /etc/hostname
      when: current_hostname.stdout != host_name

    - name: Update /etc/hosts (only if different)
      lineinfile:
        path: /etc/hosts
        regexp: "^127\\.0\\.1\\.1\\s"
        line: "127.0.1.1 {{ host_name }}"
        state: present
      when: current_hostname.stdout != host_name

    - name: Apply the hostname change (only if different)
      command: hostnamectl set-hostname "{{ host_name }}"
      when: current_hostname.stdout != host_name
      changed_when: true

    - name: Install BIND9, BIND9 Utils, and DNS Utils
      apt:
        name:
          - bind9
          - bind9utils
          - dnsutils
        state: present
        update_cache: yes
      become: yes

    - name: Copy named.conf.local to /etc/bind/
      ansible.builtin.copy:
        src: files/named.conf.local
        dest: /etc/bind/named.conf.local
        owner: root
        group: bind
        mode: '0644'
      become: yes
      notify: Restart Bind9


    - name: Copy db.home.mylab.com to /etc/bind/
      ansible.builtin.copy:
        src: files/db.home.mylab.com
        dest: /etc/bind/db.home.mylab.com
        owner: root
        group: bind
        mode: '0644'
      become: yes
      notify: Restart Bind9


    - name: Copy named.conf.options to /etc/bind/
      ansible.builtin.copy:
        src: files/named.conf.options
        dest: /etc/bind/named.conf.options
        owner: root
        group: bind
        mode: '0644'
      become: yes
      notify: Restart Bind9

  handlers:
    - name: Restart Bind9
      service:
        name: bind9
        state: restarted
      become: yes
