providers:
  file:
    directory: "/etc/traefik/config"
    watch: true

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

log:
  level: INFO  # Set to DEBUG for more details
  filePath: "/var/log/traefik/traefik.log"
