network:
 version: 2
 renderer: NetworkManager
 ethernets:
   ens18:
     dhcp4: no
     addresses: [192.168.2.41/20]
     gateway4: 192.168.2.1
     nameservers:
         addresses: [8.8.8.8,8.8.8.4]
