---
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.6.0
    container_name: openwebui
    ports:
      - "8080:8080"
    environment:
      # Ollama Config
      - OLLAMA_BASE_URL=http://ollama.example.com:11434
    volumes:
      - data:/app/backend/data:rw
    networks:
      - frontend
    restart: unless-stopped

volumes:
  data:
    driver: local

networks:
  frontend:
    external: true