
---
services:
  oracle-xe:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-xe
    networks:
      - frontend
    volumes:
      - oracle-xe-data:/opt/oracle/oradata
    ports:
      - 1521:1521
    restart: unless-stopped

volumes:
  oracle-xe-data:
    driver: local
networks:
  frontend:
    external: true
